### ISSUE TITLE
Thread safety issue

### ISSUE THREAD

**Issue by viktorklang** [clohfink/RendezvousHash#2]
Hi,

I came across this implementation and thought I'd raise these issues with you.

* The implementation of `RendezvousHash` is not thread safe since [ordered](https://github.com/clohfink/RendezvousHash/blob/master/src/main/java/com/csforge/RendezvousHash.java#L101
) is accessed without a happens-before edge with respect to the `add` and `remove` methods respectively. 

* There is no safe publication of the `RendezvousHash` constructor, so any concurrent usage would have to rely on external safe publication.

Cheers,
√

**Comment by clohfink** [comment]
Thanks for your feedback and time! I made some changes in https://github.com/clohfink/RendezvousHash/commit/8018d38fb9aefc6b60e59aacd44903c459c8cda3 I think will help, does it look sufficient to you?

**Comment by viktorklang** [comment]
Hi @clohfink,

thanks for the quick response!

I was thinking something along the lines of: https://github.com/viktorklang/RendezvousHash/commit/b7a5415c5607d8f4155ebf773098b0de1f353850

**Comment by clohfink** [comment]
Thats awesome, mind if I merge it in?

**Comment by viktorklang** [comment]
You are most welcome to merge it in!

**Comment by clohfink** [comment]
Thanks again!
